trigger: none

stages:
  - stage: Build
    displayName: Maven Build Stage
    jobs:
      - job: Build
        pool:
          name: default
          demands: maven
        steps:
          - task: Maven@1
            displayName: Maven Build stage
            inputs:
              mavenPomFile: 'pom.xml'
              goals: 'clean package'
          - task: Docker@2
            displayName: Docker build and push to ACR
            inputs:
                containerRegistry: 'ACR'
                repository: 'amazon'
                command: 'buildAndPush'
                Dockerfile: '**/Amazon-Web/Dockerfile'
                tags: |
                  $(Build.BuildId)
                  latest
                addPipelineData: false
                addBaseImageData: false